#!/usr/bin/env bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Fetching vim plugins (git submodules)..."
git -C "$DIR" submodule update --init --recursive

echo "Done."
